modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/MrLion303/AssetsLoaderMod/issues"

[[mods]]
modId="assetsloadermod"
version="1.0.0"
displayName="AssetsLoaderMod"
authors="MrLion303"
description='''Replaces Minecraft's world loading screen with a minimal vanilla-style loading indicator.'''
displayTest="MATCH_VERSION"
displayURL="https://github.com/MrLion303/AssetsLoaderMod"

[[mixins]]
config="assetsloadermod.mixins.json"

[[dependencies.assetsloadermod]]
modId="forge"
mandatory=true
versionRange="[47.2.0,48)"
ordering="NONE"
side="CLIENT"

[[dependencies.assetsloadermod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"
